version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"  #  puerto 5555 para Prisma Studio
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/mydb?schema=public"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
