-- AlterTable
ALTER TABLE "Account" ADD COLUMN     "providerType" TEXT NOT NULL DEFAULT 'oauth';

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
